version: "3.9"

services:
  app:
    build: .
    container_name: my_flask_app
    expose:
      - 5000
  
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: my_nginx
    ports:
      -"8080:80"
    depends_on:
      - app
